# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0adb57e54036d8fe214cb6741d8588e1b247f70fab33811d8c339714e4caab491e734663f5464ef9c2ef292d4f55b6a729e0367e1e245921ca74ee51b7bf0edc

test:
  secret_key_base: 44e74e124c87aa7217b73db0bab4491803aad3054d41e84810f1493588d62c8602487a001c92f60172fe5599553e80c505de3b610eac674102ef3edd798cbd27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: Settings.production.secret_key_base
